In [ ]:
# NNumPy Primer - Linkedin Learning
import numpy as np

In [ ]:
sales = [[0, 5, 155, 0, 518],[0, 1827, 616, 317, 325]]

In [8]:
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [ ]:
array_2d = np.array([range(5), range(5)])
array_2d 
# or array_2d + 1 to start from 1 instead of zero.

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [14]:
array_2d.shape

(2, 5)

In [15]:
array.shape

(5,)

In [24]:
array_2d.T #T for transpose


array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
array_2d.T.shape 

(5, 2)

In [ ]:
array_2d.ndim # dimension of array

2

In [26]:
array_2d.dtype

dtype('int32')

In [27]:
np.array(['I', 'Love', 'Python!'])

array(['I', 'Love', 'Python!'], dtype='<U7')

#### Assigment: Array Basics
Maven MegaMart

Convert a Python List in to a NumPy array and display its attributes

In [5]:
my_list = [x * 10 for x in range (1, 11)]
my_list_array = np.array(my_list).reshape(2, 5) # 2 rows 5 elements per row
my_list_array

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [6]:
print(f"Dimension: {my_list_array.ndim}")
print(f"Shape: {my_list_array.shape}")
print(f"Size: {my_list_array.size}")
print(f"dtype: {my_list_array.dtype}")

Dimension: 2
Shape: (2, 5)
Size: 10
dtype: int32


##### Array Creation

In [10]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.arange(1, 9, 2).reshape(2, 2)

array([[1, 3],
       [5, 7]])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones(52, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [31]:
np.zeros(100, dtype=int).reshape(10,10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
np.zeros((5,20), int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.zeros((5,20), int).T # Transposing 20 x 5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])