In [6]:
import numpy as np

In [ ]:
sales = [[0, 5, 155, 0, 518],[0, 1827, 616, 317, 325]]

In [8]:
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [ ]:
array_2d = np.array([range(5), range(5)])
array_2d 
# or array_2d + 1 to start from 1 instead of zero.

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [14]:
array_2d.shape

(2, 5)

In [15]:
array.shape

(5,)

In [24]:
array_2d.T #T for transpose


array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
array_2d.T.shape 

(5, 2)

In [ ]:
array_2d.ndim # dimension of array

2

In [26]:
array_2d.dtype

dtype('int32')

In [27]:
np.array(['I', 'Love', 'Python!'])

array(['I', 'Love', 'Python!'], dtype='<U7')

In [ ]:
# Assigment: Array Basics
# Maven MegaMart
# Convert a Python List in to a NumPy array and help me get familiar with its properties

my_list = [x * 10 for x in range (1, 11)]
my_list_array = np.array(my_list).reshape(2, 5) # 2 rows 5 elements per row
my_list_array

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [40]:
print(f"Dimension: {my_list_array.ndim}")
print(f"Shape: {my_list_array.shape}")
print(f"Size: {my_list_array.size}")
print(f"dtype: {my_list_array.dtype}")

Dimension: 1
Shape: (10,)
Size: 10
dtype int32
